# Coolify Configuration for SETINA Slowdown App
# This file contains deployment configuration for Coolify

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp:/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5230/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "coolify.managed=true"
      - "coolify.name=slowdown-backend"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "coolify.managed=true"
      - "coolify.name=slowdown-frontend"
      - "traefik.enable=true"
      - "traefik.http.routers.slowdown.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.slowdown.entrypoints=websecure"
      - "traefik.http.routers.slowdown.tls.certresolver=letsencrypt"
      - "traefik.http.services.slowdown.loadbalancer.server.port=80"

networks:
  default:
    name: slowdown-network
    labels:
      - "coolify.managed=true"
