version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    container_name: slowdown-backend
    ports:
      - "5230:5230"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: slowdown-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
